version: '2'
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=directus
    # publish mysql server ports to access
    # from outside of container with: mysql -h localhost -P 3306 --protocol=tcp -u directus -p
    # ports:
    #  - "3306:3306"
  directus:
    depends_on:
       - mysql
    image: getdirectus/directus:6.3
    container_name: directus
    # links:
    #  - mysql:mysql
    ports:
     - "8080:8080"
    restart: always
    # Replace ~/Development/directus with your local directus git checkout
    # volumes:
    #    - ~/Development/directus:/var/www/html
    environment:
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_DATABASE=directus
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
     - MYSQL_ENV_MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_USER=directus
